nifi:
  replicaCount: 3

  properties:
    isNode: true # Required to designate this instance as a cluster node
    sensitiveKey: developer2025
    clusterPort: 6007
    webProxyHost: nifi.nifi.svc
    # cluster communication timeouts for scaling operations
    clusterNodeConnectionTimeout: "60 sec"
    clusterNodeReadTimeout: "60 sec"
    zookeeperSessionTimeout: "60 sec"

  sts:
    startupProbe:
      enabled: true
      periodSeconds: 150

  certManager:
    enabled: true
    clusterDomain: cluster.local
    keystorePasswd: developer2025
    truststorePasswd: developer2025
    additionalDnsNames:
      - localhost
      - nifi.infra.svc
      - "*.nifi-headless.nifi.svc.cluster.local"
    refreshSeconds: 60
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
    certDuration: 2160h
    caDuration: 87660h

  auth:
    singleUser:
      username: admin
      password: developer2025 # Must to have at least 12 characters

