apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/viru-janadri/kubernetes-nifi-gitops.git
    targetRevision: HEAD
    path: charts/viru-nifi
  destination:
    server: https://kubernetes.default.svc
    namespace: nifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ReplaceResource=true
